TExt Generation using **GPT2**

In [1]:
!pip install transformers

     |████████████████████████████████| 2.1MB 14.3MB/s 
     |████████████████████████████████| 3.3MB 35.9MB/s 
     |████████████████████████████████| 901kB 32.8MB/s 


LOADING **MODEL**

In [2]:
from transformers import GPT2LMHeadModel, GPT2Tokenizer

In [3]:
tokenizer = GPT2Tokenizer.from_pretrained("gpt2")
model = GPT2LMHeadModel.from_pretrained("gpt2")


PREPROCESSING THE **DATA**

In [13]:
text = "What is Natural Language Processing?"
encoded_input = tokenizer.encode(text, return_tensors='pt')

In [14]:
encoded_input

tensor([[ 2061,   318, 12068, 15417, 28403,    30]])

In [15]:
print(tokenizer.decode(encoded_input[0][0]))
print(tokenizer.decode(encoded_input[0][1]))
print(tokenizer.decode(encoded_input[0][2]))

What
 is
 Natural


In [6]:
##encoded_input = tokenizer.encode(text, return_tensors='tf')

In [7]:
##encoded_input

<tf.Tensor: shape=(1, 6), dtype=int32, numpy=array([[ 2061,   318, 12068, 15417, 28403,    30]], dtype=int32)>


Text **Generation**

In [16]:
output = model.generate(encoded_input, max_length=500,num_beams=5,no_repeat_ngram_size=2,early_stopping=True)
output

Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.


tensor([[ 2061,   318, 12068, 15417, 28403,    30,   198,   198, 35364,  3303,
          7587,   357,    45, 19930,     8,   318,   262,  1429,   416,   543,
           356,  2193,   649,  2456,    11, 20144,    11, 13439,    11,   290,
         13439,    13,   632,   318,   257,  1429,   287,   543,   674,  3632,
         16795,   912,   777,  2456,   290, 20144,   287,   257,   835,   326,
          3578,   514,   284,  1833,   606,    13,   399, 19930,   318,   635,
          1900,   355,   366, 16129,  7587,   553,   290,   340,   318,   530,
           286,   262,   749,  1593,  7612,   286,  4673,   257,   649,  3303,
            13,   554,   428,  2708,    11,   356,   481,   804,   379,   703,
           356,   460,  2193,   284,   779,  3288,  3303,   284, 10996,   351,
           584,   661,    13,   775,   481,   635,  2112,   703,   284,  2193,
           257,  3303,   290,   703,   340,   460,   307,  5625,   284,   534,
           898,  1204,    13,   628,   198,  2437,  


Decoding The Encoded Text Genererated By **Model¶**

In [17]:
tokenizer.decode(output[0], skip_special_tokens=True)

'What is Natural Language Processing?\n\nNatural language processing (NLP) is the process by which we learn new words, phrases, sentences, and sentences. It is a process in which our brain interprets these words and phrases in a way that allows us to understand them. NLP is also known as "language processing," and it is one of the most important aspects of learning a new language. In this article, we will look at how we can learn to use natural language to communicate with other people. We will also discuss how to learn a language and how it can be applied to your own life.\n\n\nHow to Learn a Language and How to Apply it to Your Own Life\n... and What You Can Do to Improve Your Language Skills. This article will show you how you can improve your language skills by applying them to the world around you. You will learn about the different types of languages that are available in different parts of your life, as well as how they differ from one another in terms of their grammar, vocabula